
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy, Suspense } from "react";
import { RouteObject } from "react-router";

import { UserGuard } from "app";
import MainLayout from "./components/MainLayout";


const ActiveWorkoutPage = lazy(() => import("./pages/ActiveWorkoutPage.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const DashboardPage = lazy(() => import("./pages/DashboardPage.tsx"));
const GeneratingWorkoutScreen = lazy(() => import("./pages/GeneratingWorkoutScreen.tsx"));
const GymFinderPage = lazy(() => import("./pages/GymFinderPage.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const OnboardingPage = lazy(() => import("./pages/OnboardingPage.tsx"));
const ProgressPage = lazy(() => import("./pages/ProgressPage.tsx"));
const SelectDurationPage = lazy(() => import("./pages/SelectDurationPage.tsx"));
const SelectGymPage = lazy(() => import("./pages/SelectGymPage.tsx"));
const UserProfilePage = lazy(() => import("./pages/UserProfilePage.tsx"));
const WorkoutDetailsPage = lazy(() => import("./pages/WorkoutDetailsPage.tsx"));
const WorkoutRecommendationPage = lazy(() => import("./pages/WorkoutRecommendationPage.tsx"));

export const userRoutes: RouteObject[] = [
	// Landing and onboarding pages (no layout)
	{ path: "/app", element: <App />},
	{ path: "/onboarding-page", element: <UserGuard><OnboardingPage /></UserGuard>},
	{ path: "/onboardingpage", element: <UserGuard><OnboardingPage /></UserGuard>},
	{ path: "/login", element: <Suspense fallback={<div className="flex items-center justify-center h-screen">Loading...</div>}><Login /></Suspense>},

	// Landing page (no authentication required)
	{ 
		path: "/", 
		element: (
			<Suspense fallback={<div className="flex items-center justify-center h-screen"><div className="text-center"><div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin mx-auto"></div><p className="mt-2">Loading...</p></div></div>}>
				<App />
			</Suspense>
		),
		errorElement: <div className="flex items-center justify-center h-screen"><div className="text-center"><h2 className="text-2xl font-bold">Something went wrong</h2><p className="mt-2">We couldn't load the landing page. Please try again.</p></div></div>
	},
	{ path: "/dashboard", element: <UserGuard><MainLayout><DashboardPage /></MainLayout></UserGuard>},
	{ path: "/active-workout-page", element: <UserGuard><MainLayout><ActiveWorkoutPage /></MainLayout></UserGuard>},
	{ path: "/activeworkoutpage", element: <UserGuard><MainLayout><ActiveWorkoutPage /></MainLayout></UserGuard>},
	{ path: "/dashboard-page", element: <UserGuard><MainLayout><DashboardPage /></MainLayout></UserGuard>},
	{ path: "/dashboardpage", element: <UserGuard><MainLayout><DashboardPage /></MainLayout></UserGuard>},
	{ path: "/generating-workout-screen", element: <UserGuard><MainLayout><GeneratingWorkoutScreen /></MainLayout></UserGuard>},
	{ path: "/generatingworkoutscreen", element: <UserGuard><MainLayout><GeneratingWorkoutScreen /></MainLayout></UserGuard>},
	{ path: "/gym-finder-page", element: <UserGuard><MainLayout><GymFinderPage /></MainLayout></UserGuard>},
	{ path: "/gymfinderpage", element: <UserGuard><MainLayout><GymFinderPage /></MainLayout></UserGuard>},
	{ path: "/logout", element: <UserGuard><MainLayout><Logout /></MainLayout></UserGuard>},
	{ path: "/progress-page", element: <UserGuard><MainLayout><ProgressPage /></MainLayout></UserGuard>},
	{ path: "/progresspage", element: <UserGuard><MainLayout><ProgressPage /></MainLayout></UserGuard>},
	{ path: "/select-duration-page", element: <UserGuard><MainLayout><SelectDurationPage /></MainLayout></UserGuard>},
	{ path: "/selectdurationpage", element: <UserGuard><MainLayout><SelectDurationPage /></MainLayout></UserGuard>},
	{ path: "/select-gym-page", element: <UserGuard><MainLayout><SelectGymPage /></MainLayout></UserGuard>},
	{ path: "/selectgympage", element: <UserGuard><MainLayout><SelectGymPage /></MainLayout></UserGuard>},
	{ path: "/user-profile-page", element: <UserGuard><MainLayout><UserProfilePage /></MainLayout></UserGuard>},
	{ path: "/userprofilepage", element: <UserGuard><MainLayout><UserProfilePage /></MainLayout></UserGuard>},
	{ path: "/workout-details-page", element: <UserGuard><MainLayout><WorkoutDetailsPage /></MainLayout></UserGuard>},
	{ path: "/workoutdetailspage", element: <UserGuard><MainLayout><WorkoutDetailsPage /></MainLayout></UserGuard>},
	{ path: "/workout-recommendation-page", element: <UserGuard><MainLayout><WorkoutRecommendationPage /></MainLayout></UserGuard>},
	{ path: "/workoutrecommendationpage", element: <UserGuard><MainLayout><WorkoutRecommendationPage /></MainLayout></UserGuard>},

	// New pages for the navbar items
	{ path: "/history", element: <UserGuard><MainLayout><DashboardPage /></MainLayout></UserGuard>}, // Placeholder for History page
	{ path: "/settings", element: <UserGuard><MainLayout><UserProfilePage /></MainLayout></UserGuard>}, // Using UserProfile as placeholder for settings
	{ path: "/community", element: <UserGuard><MainLayout><DashboardPage /></MainLayout></UserGuard>}, // Placeholder for Community page
	{ path: "/explore", element: <UserGuard><MainLayout><GymFinderPage /></MainLayout></UserGuard>}, // Using GymFinder as placeholder for explore

];
